$(function(){
$('.grid').click(function(){location.href = 'publicacion.html';})
$('.noti').click(function(){location.href = 'publicacion.html';})
$('#auth_ps4_pro').click(function(){location.href = 'post_ps4_pro_auth.html';})
$('#auth_ps4_TLOU').click(function(){location.href = 'post_ps4_TLOU_auth.html';})
$('#auth_ps4_VR').click(function(){location.href = 'post_ps4_VR_auth.html';})
$('#auth_ps4_GOW').click(function(){location.href = 'post_ps4_GOW_auth.html';})
$('#auth_ps4_10').click(function(){location.href = 'post_ps4_TOP10_auth.html';})
$('#auth_xbox_one').click(function(){location.href = 'post_xbox_auth.html';})
$('#auth_xbox_dayz').click(function(){location.href = 'post_xbox_dayz_auth.html';})
$('#auth_xbox_gears').click(function(){location.href = 'post_xbox_gears_auth.html';})
$('#auth_xbox_forza').click(function(){location.href = 'post_xbox_forza_auth.html';})
$('#auth_xbox_halo').click(function(){location.href = 'post_xbox_halo_auth.html';})
$('#ps4_pro').click(function(){location.href = 'post_ps4_pro.html';})
$('#ps4_TLOU').click(function(){location.href = 'post_ps4_TLOU.html';})
$('#ps4_VR').click(function(){location.href = 'post_ps4_VR.html';})
$('#ps4_GOW').click(function(){location.href = 'post_ps4_GOW.html';})
$('#ps4_10').click(function(){location.href = 'post_ps4_TOP10.html';})
$('#xbox_one').click(function(){location.href = 'post_xbox.html';})
$('#xbox_dayz').click(function(){location.href = 'post_xbox_dayz.html';})
$('#xbox_gears').click(function(){location.href = 'post_xbox_gears.html';})
$('#xbox_forza').click(function(){location.href = 'post_xbox_forza.html';})
$('#xbox_halo').click(function(){location.href = 'post_xbox_halo.html';})
});